# background_opacity 0.8
# background #ffffff
# foreground #000000
font_size 12

shell zsh

editor /opt/homebrew/bin/nvim

macos_option_as_alt both 

# Explicitly map Option+arrows if needed
map alt+left send_text all \x1bb
map alt+right send_text all \x1bf
map alt+up send_text all \x1b[1;3A
map alt+down send_text all \x1b[1;3B

# Cmd+arrows for line navigation (bonus)
map cmd+left send_text all \x01
map cmd+right send_text all \x05

map cmd+backspace send_text all \x15
map cmd+n send_key ctrl+s send_key n 
map cmd+s send_key ctrl+s send_key b 
# map cmd+j send_key ctrl+s send_key j 
# map cmd+j send_text all \x13j
map cmd+j combine : send_key ctrl+s : send_key j
map cmd+m send_key ctrl+s send_key m 

cursor_trail 10
cursor_trail_start_threshold 0 
cursor_trail_decay 0.01 0.05
cursor_shape block
cursor_blink true 

# dynamic_background_opacity yes
scrollback_pager_history_size 500
scrollback_lines 50000
# BEGIN_KITTY_THEME
# Ayu Light
include current-theme.conf
# END_KITTY_THEME
#
#
#
# ------ OPTIMIZE KEYBOARD TO SCREEN DELAY
input_delay 0
repaint_delay 2
sync_to_monitor no
wayland_enable_ime no


# cursor animation
cursor_trail 1

cursor_trail_decay 0.1 0.2
